# Changes here will be overwritten by Copier
_commit: 6e49531
_src_path: https://github.com/pawamoy/copier-poetry.git
author_email: pawamoy@pm.me
author_fullname: "Timoth\xE9e Mazzucotelli"
author_username: pawamoy
copyright_date: '2020'
copyright_holder: "Timoth\xE9e Mazzucotelli"
copyright_holder_email: pawamoy@pm.me
copyright_license: ISC License
project_description: Rename and move files using metadata from online databases.
project_name: mvodb
python_package_command_line_name: mvodb
python_package_distribution_name: mvodb
python_package_import_name: mvodb
repository_name: mvodb
repository_namespace: pawamoy
repository_provider: github.com
