site_name: "mvodb"
site_description: "Rename and move files using metadata from online databases."
site_url: "https://pawamoy.github.io/mvodb"
repo_url: "https://github.com/pawamoy/mvodb"
repo_name: "pawamoy/mvodb"

nav:
  - Overview: index.md
  - API Reference:
    - cli.py: reference/cli.md
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Changelog: changelog.md
  - Credits: credits.md

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: purple

extra_css:
  - css/mkdocstrings.css

markdown_extensions:
  - admonition
  - markdown_include.include
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/mvodb
